# Generated by Django 4.1.9 on 2023-06-17 14:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='respuesta',
        ),
        migrations.AddField(
            model_name='faqpage',
            name='body',
            field=wagtail.fields.StreamField([('faq', wagtail.blocks.StructBlock([('pregunta', wagtail.blocks.CharBlock(max_length=255)), ('respuesta', wagtail.blocks.CharBlock(max_length=255))], icon='user'))], blank=True, null=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='wagsite_faq.faqpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
