# Generated by Django 4.1.9 on 2023-06-23 14:32

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_faq', '0002_remove_faqpage_pregunta_remove_faqpage_respuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
