# Generated by Django 4.1.9 on 2023-06-13 02:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=100, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Links',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(help_text='Texto del vínculo', max_length=255, verbose_name='Texto')),
                ('link_url', models.URLField(help_text='Dirección URL [Si es un vínculo local, seleccione el resto de la URL que no incluye el nommbre de dominio]', max_length=255, verbose_name='Url')),
                ('link_title', models.CharField(help_text='Se colocará en el atributo "Title" del hipervínculo', max_length=255, verbose_name='Título')),
                ('link_target', models.CharField(choices=[('_self', 'Misma pestaña'), ('_blank', 'Nueva pestaña'), ('_parent', 'Ventana padre'), ('_top', 'Ventana superior'), ('new', 'Nueva ventana')], default='_self', help_text='Destino donde se abrirá el vínculo', max_length=10, verbose_name='Destino')),
                ('link_order', models.IntegerField(default=1, verbose_name='Orden')),
                ('link_board', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='links', to='wagsite_links.linkboard')),
                ('link_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image', verbose_name='Ícono')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
