# Generated by Django 4.1.9 on 2023-06-12 19:45

from django.db import migrations
import wagsite_streams.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_services', '0005_alter_services_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=wagtail.fields.StreamField([('Descripcion', wagsite_streams.blocks.RichtextBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
