# Generated by Django 4.1.9 on 2023-06-19 20:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_services', '0006_alter_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='content',
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.AddField(
            model_name='services',
            name='body',
            field=wagtail.fields.StreamField([('servicio', wagtail.blocks.StructBlock([('title', wagtail.blocks.RichTextBlock(help_text='Añade tu título', required=True)), ('icon', wagtail.blocks.CharBlock(help_text='Añade tu icono de awesome', required=True)), ('text', wagtail.blocks.CharBlock(help_text='Añade tu icono de awesome', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))], icon='user'))], default=True, use_json_field=True),
            preserve_default=False,
        ),
    ]
