# Generated by Django 4.1.9 on 2023-06-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_services', '0007_remove_services_content_remove_services_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesindexpage',
            name='intro',
        ),
    ]
