# Generated by Django 4.1.9 on 2023-06-19 22:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_services', '0009_alter_services_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='body',
            field=wagtail.fields.StreamField([('servicio', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Añade tu título', required=True)), ('icon', wagtail.blocks.CharBlock(help_text='Añade tu icono de awesome', required=True)), ('text', wagtail.blocks.CharBlock(help_text='Añade una descripcion', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image'))], icon='user'))], use_json_field=True),
        ),
    ]
