# Generated by Django 4.1.9 on 2023-06-16 13:39

from django.db import migrations
import wagsite_streams.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='content',
            field=wagtail.fields.StreamField([('Evento', wagsite_streams.blocks.RichtextBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
