# Generated by Django 4.1.9 on 2023-06-24 13:58

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_teams', '0002_alter_teampage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='body',
            field=wagtail.fields.StreamField([('team_member', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=255)), ('role', wagtail.blocks.CharBlock(max_length=255)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('social_media', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=255)), ('url', wagtail.blocks.URLBlock())], label='Social Network')))], icon='user'))], use_json_field=True),
        ),
    ]
