# Generated by Django 4.1.9 on 2023-06-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutIndexPage',
        ),
    ]
