# Generated by Django 4.1.9 on 2023-06-19 20:26

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_about', '0002_delete_aboutindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.StreamField([('propiedad', wagtail.blocks.StructBlock([('order', wagtail.blocks.IntegerBlock()), ('name', wagtail.blocks.CharBlock(max_length=255)), ('descripcion', wagtail.blocks.RichTextBlock(max_length=255))], icon='user'))], use_json_field=True),
        ),
    ]
