# Generated by Django 4.1.9 on 2023-06-22 15:07

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagsite_about', '0003_alter_aboutpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
